#!/usr/bin/env bash
# Install a nginx web server listening on port 80.
#
# Also, when querying nginx at its root / with a GET
# request, it returns a page that contains the string
# 'Holberton School'.
# redirect url

apt update
apt install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

new_config=\
"server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    location / {
        try_files \$uri \$uri/ =404;
    }
    location = /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4
    }

        error_page 404 /404.html;
        location  /404.html {
            internal;
        }
    }
"
echo "$new_config" > /etc/nginx/sites-available/default
if [ "$(pgrep nginx)" -le 0 ];
then
    service nginx start
else
    service nginx restart
fi;
